#!/bin/bash

set -e

install_root="$DEPENDABOT_NATIVE_HELPERS_PATH"
if [ -n "$install_root" ] && ! [[ "$install_root" =~ ^/ ]]; then
  echo "DEPENDABOT_NATIVE_HELPERS_PATH must be an absolute path"
  exit 1
fi

helpers_dir="$(dirname "${BASH_SOURCE[0]}")"
cd $helpers_dir

install_dir="${install_root:-$(pwd)/../../tmp/helpers}/go_modules"

echo "> installing go_modules helpers to $install_dir"

os="$(uname -s | tr '[:upper:]' '[:lower:]')"

echo "> building $install_dir/helper"
GO111MODULE=on GOOS="$os" GOARCH=amd64 go build -o "$install_dir/helper" .

echo "> done"
