#!/bin/bash

set -e

install_dir=$1
if [ -z "$install_dir" ]; then
  echo "usage: $0 INSTALL_DIR"
  exit 1
fi

mkdir -p "$install_dir"
git clone https://github.com/pyenv/pyenv "$install_dir/pyenv"
(cd "$install_dir/pyenv" && git checkout v1.2.8)

echo "export PYENV_ROOT=\"$install_dir/pyenv\"" >  "$install_dir/env"
echo 'export PATH="$PYENV_ROOT/bin:$PATH"'      >> "$install_dir/env"
source "$install_dir/env"

pyenv install 2.7.15
pyenv install 3.6.7
pyenv global 3.6.7
